---
- name: Add Node source repo
  raw: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"

- name: Installing Mysql  and dependencies
  package:
     name: "{{ item }}"
     state: present
  with_items: 
    - nodejs
    - python39
    - wget

- name: Download Go Binary
  raw: "wget https://dl.google.com/go/go1.18.3.linux-amd64.tar.gz"

- name: Clean old and install new Go
  raw: "rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz"

- name: Add Go to PATH
  raw: "export PATH=$PATH:/usr/local/go/bin"

- name: Cleanup go binary
  file:
    path: /root/go1*
    state: absent