--- 
    - name: Remove existing files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - artefacts/details.yaml
        - other_plays.yaml
        - ansible.cfg
        - inventory
        
        
    - name: Initialize Build files
      template:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
      with_items:
          - { src: "details.j2", dest: "artefacts/details.yaml" }
          - { src: ansible.j2, dest: "ansible.cfg" }
    

      

