---    
  - name: Cleanup Install Environment    
    file:
       path: "{{ item }}"
       state: absent
    with_items:
        - "inventory"
        - "ansible.cfg"
        - "other_plays.yaml"
        - "/var/www/html/rhel"
        - "/var/lib/tftpboot/pxelinux"

  - name: Task Completion alert
    debug:
      msg: "Deployment Completed!!!"

    
    