---
- name: Add mongoDB repo
  copy:
     src: mongodb-org-5.0.repo
     dest: /etc/yum.repos.d/
     mode: '0777'

- name: Installing MongoDB
  package:
      name: mongodb-org
      state: present

- name: Start and enable mongodb service
  service:
    name: mongod
    state: started

- name: Allow firewall port for mongod
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled

- name: Reload firewall for mysql and mongod firewall rules
  raw: "firewall-cmd --reload"
